name: cp_api
description: ""
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_native_splash: ^2.4.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
    color: "#f2f2f2"
    image: assets/png/splash.png
    fullscreen: true
    android: true
    android_screen_orientation: portrait
    android_12:
      image: assets/png/splash.png
      color: "#f2f2f2"

flutter:
  uses-material-design: true
  assets:
    - assets/png/splash.png
